language: python
python:
  - "2.7"
cache: apt
before_install:
    - sudo add-apt-repository -y ppa:glondu/ppa
    - sudo apt-get update
    - # sudo apt-get install ocaml ocaml-native-compilers camlp5 coq
    - sudo apt-get install coq-8.4
    - coqc --version || echo debug
    - coq_makefile -h || echo debug
    - export COQPATH=$COQPATH:.
    - # export OTHERFLAGS=-verbose  # for coqc via coq_makefile
    - pip install -r requirements.text
env:
    - TARGET=src
    - TARGET=sandbox
script:
    - make $TARGET
