before_install:
    - sudo apt-get update
    - sudo apt-get install ocaml ocaml-native-compilers camlp5 coq
    - coqc --version || echo debug
    - coq_makefile -h || echo debug
    - export COQPATH=$COQPATH:.
    - export OTHERFLAGS=-verbose  # for coqc via coq_makefile
script:
    - (cd src ; ./make.sh)
